# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: default

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Eticat
      run: dotnet build --no-restore EtiCat
    - name: CI
      run: dotnet run --no-build EtiCat -- ci --prerelease ${{ steps.extract_branch.outputs.branch }}
    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: EtiCat Nuget Package
        path: Eticat/**/*.nupkg
